### ISSUE TITLE
dffml:plugins  github actions fails on adding a new plugin 

### ISSUE THREAD

**Issue by Pratikrocks** [intel/dffml#1046] opened 2021-03-17 03:30 UTC

**Comment by pranav-msc** [comment] 2021-03-19 02:44
Can you please exactly describe your error,like on running which command are you facing an error and upload screenshot of the same

**Comment by Pratikrocks** [comment] 2021-03-19 03:13
Hi @pranav-msc for reference you can look https://github.com/intel/dffml/pull/1027/checks?check_run_id=2127448442#step:9:8100

**Comment by programmer290399** [comment] 2021-03-20 08:02
The test that is failing is ` test_all_plugins_have_pypi_tokens`, and this is because when you are creating a new plugin it has no token associated with it.

As you can see in the documentation [here]( https://intel.github.io/dffml/contributing/codebase.html#adding-a-new-plugin)  it says that after adding a plugin you need to open an issue to get that pypi token.  

If the error persists after adding the token in its appropriate place as documented , then I think it may be a bug.

otherwise it's fine @Pratikrocks .

**Comment by Pratikrocks** [comment] 2021-03-21 12:29
Hi @programmer290399 I appended in `plugins` area hee https://github.com/intel/dffml/pull/1027/files#diff-2e2d435c7f3858b5b83b4f59a58b8b0669c95081f96cafe6254fc70aa24cea16R58 but still am getting this error

**Comment by programmer290399** [comment] 2021-03-21 13:11
Yes , 

So adding the plugin name to 

* ` .github/workflows/testing.yml` will help you pass the test `test_all_plugins_being_tested`.
* `dffml/plugins.py` will help you pass the test `test_all_plugins_appear_in_dffml_plugins`

But there is a third test 

`test_all_plugins_have_pypi_tokens` , which checks if your plugin has a pypi token or not , 

>All these tests are under `dffml/tests/test_ci.py`. 

And as I mentioned above that pypi token would only be generated when you open an issue to obtain one. 

Also I couldn't find an issue with a format `pypi: Add token for dffml-{PLUGIN_TYPE}-{NAME} to testing.yml`  so I am also not very sure about the process beyond that  but I think it might not be a bug , 

is there any other test that is failing @Pratikrocks ? which is not mentioned above ......

**Comment by Pratikrocks** [comment] 2021-03-21 13:14
no only those were failing

**Comment by programmer290399** [comment] 2021-03-21 16:09
Then I think it is not a bug , if @pdxjohnny  confirms this then we can close this issue , otherwise we can resolve it. 

Also I think that when we create a plugin with `dffml service dev create` command , I think it should also add the plugin name and type in the above two lists automatically. Just a small enhancement ....

**Comment by pdxjohnny** [comment] 2021-03-23 14:55
> Also I think that when we create a plugin with `dffml service dev create` command , I think it should also add the plugin name and type in the above two lists automatically. Just a small enhancement ....

We actually don't want this, we are going to move all the plugins out of the main source repo into the dffml org. We can discuss this in the meeting today

**Comment by programmer290399** [comment] 2021-03-24 03:12
As discussed in the weekly sync yesterday, I think we can close this issue @Pratikrocks.

For reference and more information : 
* Weekly Sync 2021-03-23 @
    - [1:15:22](https://youtu.be/Gl7WQbl7Xz0?t=4505)
    - [0:56:45](https://youtu.be/Gl7WQbl7Xz0?t=3405)
* Weekly Sync Doc (See Housekeeping under Tuesday March 23rd 2021) [here](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqazFJN3AxclBIX2d0VE8yVHl1RkNzRTNFWm0tZ3xBQ3Jtc0trN05wTDhnQ1pKQ2JGUkNSdmJNMUR3QXVrUnlGb2x2a3BCakw3VXpkUFBrMEVEWFRKMkxDYTZwVEdmemZuQk0ya2ZsNFp4bDdhYVJ0WUdTbVUwTFU1MW5TVXgwQl8yZGlWTEZLWWJKU2JEVW9jUWFDVQ&q=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F16u9Tev3O0CcUDe2nfikHmrO3Xnd4ASJ45myFgQLpvzM%2Fedit%23heading%3Dh.hpxn2mfk6sm3)

**Closed** 2021-03-24 03:13 UTC
Labels: bug
